project:
  type: website
  output-dir: docs

filters:
  - extensions/rtex.lua
bibliography: references.bib
# csl: glossa.csl
reference-location: margin
citation-location: margin

website:
  search:
    location: sidebar
    type: overlay
    copy-button: true
  title: "Sokoly Research"
  navbar:
    left:
      - text: "Research"
        menu:
          - text: "Machine Learning"
            href: machine-learning.qmd
          - text: "Formal Science"
            href: formal-science.qmd
          - text: "Projects"
            href: projects.qmd
      - href: about.qmd
        text: About
      - href: who-we-are.qmd
        text: "Who We Are"
  page-footer:
    border: true
    background: light
    left:
      - text: "Copyright &copy; 2025 Sokoly Research. All Rights Reserved."
    right:
      - href: mailto:rector@sokoly.science
        text: "rector@sokoly.science"
format:
  html:
    theme: simplex
      # - cosmo
      # - brand 
    css: styles.css
    toc: true
    toc-depth: 6
    grid: 
        margin-width: 300pt
