project:
  type: website
  output-dir: docs

website:
  title: "Sokoly Research Institute • 救國隼教研團"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: simplex
      # - cosmo
      # - brand
    css: styles.css
    toc: true
