project:
  type: website
  output-dir: docs

filters:
  - extensions/rtex.lua
bibliography: references.bib
# csl: glossa.csl
reference-location: margin
citation-location: margin

website:
  search:
    location: sidebar
    type: overlay
    copy-button: true
  title: "Sokoly Research Institute • 救國隼教研團"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: simplex
      # - cosmo
      # - brand
    css: styles.css
    toc: true
    toc-depth: 6
    grid: 
        margin-width: 300pt
